[project]
name = "greythr-clone-app-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx2>=2.12.0",
    "passlib>=1.7.4",
    "pydantic[email]>=2.13.5",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "9.0"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--strict-markers", "--strict-config"]

[tool.coverage.run]
branch = true
source = ["."]
omit = [
    "*/tests/*", 
    "*/__pycache__/*", 
    "*/.venv/*", 
    "*/database/common.py", 
    "*/database/database.py", 
    "*/main.py"
    ]

[tool.coverage.report]
show_missing = true
skip_covered = true
precision = 2

[tool.coverage.html]
directory = "htmlcov"